version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/SNS-OhLife
    overwrite: yes
file_exist_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu