name: CI-CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: onlycodedeploy
  CODE_DEPLOY_APPLICATION_NAME: CODE-DEPLOY-OHLIFE
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CODE-DEPLOY-GROUP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with: 
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Make file zip
        run: zip -r ./SGITHUB_SHA .
        shell: bash

      - name: Configuration AWS credentals
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
                
      - name: Upload to s3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://onlycodedeploy/$GITHUB_SHA.zip

      - name: Code Deploy
        run:
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB.SHA.zip
